# Generated by Django 5.2 on 2025-05-11 06:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 5, 11, 6, 44, 56, 823080, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
